<!--meta tag facebook-->

<meta property="og:type"               content="website" />
<meta property="og:title"              content="<?= $block->getMetaTitle() ?>" />
<meta property="og:description"        content="<?= $block->getMetaDescription() ?>" />
<meta property="og:image"              content="<?= $block->getImagePreview() ?>" />
<!--meta tag twitter-->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="<?= $block->getMetaTitle() ?>">
<meta name="twitter:description" content="<?= $block->getMetaDescription() ?>">
<meta name="twitter:image" content="<?= $block->getImagePreview() ?>">